### ISSUE TITLE
从github上拉取项目到本地后，用android studio，直接运行项目，apk没有安装到手机上(已解决，麻烦关闭这个issue)

### ISSUE THREAD

**Issue by jackom** [py-novel/client_mobile_flutter#6]
从github上拉取项目到本地后，用android studio，直接运行项目(没报错)，apk没有安装到手机上。我用 flutter doctor 命令检查没发现需要安装的插件啥的，用flutter官方的demo能正常安装apk到手机上，这种情况怎么解决的呢？我目前是下载apk去安装体验。

**Comment by jackom** [comment]
已经解决了，麻烦楼主关闭这个issue。

1、我先屏蔽掉这里的代码；
![image](https://user-images.githubusercontent.com/5052960/71710319-a20b9080-2e36-11ea-9e83-4b7afb3577d7.png)
2、再通过 flutter upgrade更新：
![image](https://user-images.githubusercontent.com/5052960/71710348-cb2c2100-2e36-11ea-8bd4-e9e4069f9e56.png)
3、最后 直接运行项目就正常跑起来了。

如果还是不行，还要 build apk的方式：
![image](https://user-images.githubusercontent.com/5052960/71710666-6bcf1080-2e38-11ea-83c6-b0980b20cb40.png)

**Comment by dkvirus** [comment]
感谢您的解答。
