### ISSUE TITLE
试读之后怎么加入书架

### ISSUE THREAD

**Issue by littletow** [py-novel/client_mobile_flutter#8]
关联#5

**Comment by littletow** [comment]
能否在章节内添加加入书架功能

**Comment by dkvirus** [comment]
@eagle-1949 

我准备参考 QQ 阅读的做法，在试读小说页面想要返回上一页面时，拦截返回键，从下往上弹出对话框，让用户选择是 `加入书架` 还是 `确定退出`。

如果你有更好的交互方式，欢迎留言！

**Comment by dkvirus** [comment]
- 修复 `加入书架` 按钮无效的问题；（原因：token 过期，没有自动刷新）
- 优化试读功能，退出试读页面时弹框提示用户是否加入书架；
- 优化详情页面，判断书籍是否已存在书架；
